### ISSUE TITLE
I get url of the links

### ISSUE THREAD

**Issue by NourdineMazali** [DoersGuild/jQuery.print#38]
Why are the urls of the links in html are shown in the print? 
Thank you

**Comment by sathvikp** [comment]
That is a standard printing behaviour, you can hide them with a bit of CSS as outlined in this SO question: http://stackoverflow.com/a/12051232/937891

```css
@media print {
  a[href]:after {
   content: "";
  }
}
```
