### ISSUE TITLE
hide href links

### ISSUE THREAD

**Issue by easdev** [DoersGuild/jQuery.print#58]
Hi - how do you hide the href links, but still print the text within the link? TQ

**Comment by sathvikp** [comment]
Please see http://stackoverflow.com/a/12051232/937891

```css
@media print {
  a[href]:after {
    content: none !important;
  }
}
```
